AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
 iBelieveAPIServicesStack

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 20

  # API Gateway resource
  # API Gateway resource

Parameters:
  Stage:
    Type: String
    Description: Stage name to deploy resources to
    Default: dev
    AllowedValues:
      - dev
      - stage
      - production
Resources:
  ibelieveApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: !Sub "ibelieveApi-${Stage}"
      StageName: !Ref Stage
      Variables:
        LAMBDA_ALIAS: !Ref Stage
      TracingEnabled: true

  PostStyleQuizFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      FunctionName: PostStyleQuiz
      Description: Updates Style Quiz details into table
      CodeUri: style-quiz-service
      Handler: ai.ibelieve.StyleQuizApp::handleRequest
      Runtime: java11
      Architectures:
        - x86_64
      MemorySize: 512
      Policies:
        # Give the Lambda service access to poll your DynamoDB Stream
        - AmazonDynamoDBFullAccess
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          STYLE_QUIZ_TABLE: StyleQuiz
      Events:
        StyleQuizApiEvent:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /v1/stylequiz
            Method: post
            RestApiId: !Ref ibelieveApi
  GetStyleQuizFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      FunctionName: GetStyleQuiz
      Description: Get StyleQuiz By ID
      CodeUri: style-quiz-service
      Handler: ai.ibelieve.StyleQuizApp::handleRequest
      Runtime: java11
      Architectures:
        - x86_64
      MemorySize: 512
      Policies:
        # Give the Lambda service access to poll your DynamoDB Stream
        - AmazonDynamoDBFullAccess
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          STYLE_QUIZ_TABLE: StyleQuiz
      Events:
        StyleQuizApiEvent:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /v1/stylequiz
            Method: get
            RestApiId: !Ref ibelieveApi
  PostUserFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      FunctionName: PostUser
      Description: Updates User details into table
      CodeUri: user-service
      Handler: ai.ibelieve.UserApp::handleRequest
      Runtime: java11
      Architectures:
        - x86_64
      MemorySize: 512
      Policies:
        # Give the Lambda service access to poll your DynamoDB Stream
        - AmazonDynamoDBFullAccess
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          USER_TABLE: User
      Events:
        UserApiEvent:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /v1/user
            Method: post
            RestApiId: !Ref ibelieveApi
  GetUserFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      FunctionName: GetUser
      Description: Get User By ID
      CodeUri: user-service
      Handler: ai.ibelieve.UserApp::handleRequest
      Runtime: java11
      Architectures:
        - x86_64
      MemorySize: 512
      Policies:
        # Give the Lambda service access to poll your DynamoDB Stream
        - AmazonDynamoDBFullAccess
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          USER_TABLE: User
      Events:
        UserApiEvent:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /v1/user
            Method: get
            RestApiId: !Ref ibelieveApi
Outputs:
  StyleApiEndpoint:
    Description: "API endpoint"
    Value: !Sub "https://${ibelieveApi}.execute-api.${AWS::Region}.amazonaws.com/${Stage}/v1/stylequiz"
  UserApiEndpoint:
    Description: "API endpoint"
    Value: !Sub "https://${ibelieveApi}.execute-api.${AWS::Region}.amazonaws.com/${Stage}/v1/user"